//This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsFacenet = 'assets/facenet.tflite';
  static const String assetsMobileFaceNet =
      'assets/mobile_face_net.tflite';
  static const String imagesLogo = 'images/logo.png';
}
